export const LABELS = {
  ro: {
    nav: {
      home: 'Acasă',
      myAccount: 'Contul meu',
      tools: 'Tools',
      signOut: 'Deconectare',
      signIn: 'Conectare',
    },
    acasa: {
      slides: [
        {
          heading: 'Devino consultant',
          sub: 'Oferă-ți expertiza fiscală și construiește-ți clientela pe Servio.',
          cta: 'Află mai mult',
        },
        {
          heading: 'Găsește un consultant',
          sub: 'Conectează-te cu cei mai buni consultanți fiscali în câțiva pași.',
          cta: 'Caută acum',
        },
      ],
    },
    catalogue: {
      stats: {
        available: 'Consultanți disponibili',
        specialisations: 'Specializări',
        avgRate: 'Tarif mediu/oră',
      },
      filters: {
        specialisation: 'Specializare',
        maxRate: (max) => `Tarif maxim: €${max}`,
        availableToday: 'Disponibili astăzi',
        sortBy: 'Sortare după',
        sortOptions: {
          relevance: 'Relevanță',
          rateAsc: 'Tarif (mic → mare)',
          rateDesc: 'Tarif (mare → mic)',
          name: 'Nume',
        },
      },
      noResults: 'Nu s-au găsit consultanți.',
    },
    consultantCard: {
      viewProfile: 'Vezi profilul',
      perHour: '/ oră',
    },
    statusLabels: {
      pending: 'Așteptare plată',
      pending_confirmation: 'Așteptare confirmare',
      ping_pong: 'Info suplimentară',
      ping_pong_final_day: 'Zi finală',
      auto_confirmed: 'Confirmat automat',
      confirmed: 'Confirmat',
      in_progress: 'În desfășurare',
      completed: 'Finalizat',
      cancelled: 'Anulat',
      disputed: 'Disputat',
      closed: 'Închis',
      auto_closed: 'Închis automat',
      retry_payment: 'Reîncercare plată',
    },
    statusTips: {
      pending: 'Plata este în curs.',
      pending_confirmation: 'Plata a fost primită. Se așteaptă confirmarea consultantului.',
      confirmed: 'Consultantul a confirmat. Sesiunea ta este programată.',
      completed: 'Sesiunea s-a încheiat cu succes.',
      cancelled: 'Această sesiune a fost anulată.',
    },
    dashboard: {
      tabs: {
        overview: 'Rezumat',
        sessions: 'Sesiunile mele',
        availability: 'Disponibilitate',
        profile: 'Profilul meu',
        settings: 'Setări cont',
      },
    },
    clientDashboard: {
      tabs: {
        sessions: 'Sesiunile mele',
        settings: 'Setări cont',
      },
    },
    overview: {
      welcomeBack: (name) => `Bun venit, ${name}.`,
      activitySummary: 'Iată un rezumat al activității tale.',
      kpi: {
        upcoming: 'Sesiuni viitoare',
        pendingConfirmation: 'Așteptare confirmare',
        completedThisMonth: 'Finalizate luna aceasta',
        total: 'Total sesiuni',
      },
      upcomingTitle: 'Sesiuni viitoare',
      noUpcoming: 'Nu ai sesiuni viitoare.',
      seeDetails: 'Vezi detalii',
    },
    sessionsTab: {
      title: 'Sesiunile mele',
      checking: 'Se verifică…',
      refresh: '↻ Reîncarcă',
      loading: 'Se încarcă…',
      noSessions: 'Nu ai sesiuni.',
      filterAll: 'Toate',
      columns: {
        client: 'Client',
        dateTime: 'Dată & Oră',
        status: 'Status',
        notes: 'Note',
        actions: 'Acțiuni',
      },
      seeDetails: 'Vezi detalii',
      confirm: 'Confirmă',
      settingUpRoom: 'Se configurează sala…',
      join: 'Intră',
    },
    mySessionsPanel: {
      title: 'Sesiunile mele',
      loading: 'Se încarcă…',
      noSessions: 'Nu ai sesiuni rezervate.',
      refresh: '↻ Reîncarcă',
      checking: 'Se verifică…',
      seeDetails: 'Vezi detalii',
      join: 'Intră',
      cancel: 'Anulează',
      settingUpRoom: 'Se configurează sala…',
      confirmModal: {
        title: 'Ești sigur?',
        message: 'Aceasta va anula sesiunea și va elibera intervalul orar. Acțiunea nu poate fi anulată.',
        goBack: 'Înapoi',
        confirmCancel: 'Da, anulează sesiunea',
        cancelling: 'Se anulează…',
      },
      columns: {
        consultant: 'Consultant',
        dateTime: 'Dată & Oră',
        status: 'Status',
        actions: 'Acțiuni',
      },
    },
    accountSettings: {
      financial: {
        title: 'Financiar',
        loading: 'Se încarcă…',
        active: 'Activ — plățile sunt direcționate automat',
        incompleteOnboarding: 'Onboarding incomplet — finalizează configurarea',
        stripeId: 'Stripe ID',
        completeOnboarding: 'Finalizează onboarding-ul',
        checkStatus: 'Verifică statusul',
        checking: 'Se verifică…',
        redirecting: 'Se redirecționează…',
        noAccount: 'Nu ai un cont Stripe conectat. Conectează-te pentru a primi plățile direct în contul tău bancar.',
        connectStripe: 'Conectează cont Stripe',
      },
      changeEmail: {
        title: 'Schimbă adresa de email',
        newEmail: 'Nouă adresă de email',
        placeholder: 'nou-email@exemplu.ro',
        save: 'Actualizează emailul',
        saving: 'Se salvează…',
        success: '✓ Adresa de email a fost actualizată.',
        error: 'A apărut o eroare.',
      },
      changePassword: {
        title: 'Schimbă parola',
        currentPassword: 'Parola actuală',
        newPassword: 'Parolă nouă',
        confirmPassword: 'Confirmă parola nouă',
        save: 'Actualizează parola',
        saving: 'Se salvează…',
        success: '✓ Parola a fost actualizată.',
        mismatch: 'Parolele nu se potrivesc.',
        error: 'A apărut o eroare.',
      },
      dangerZone: {
        title: 'Zonă periculoasă',
        deleteAccount: 'Șterge contul',
        deleting: 'Se șterge…',
        confirmMessage: 'Ești sigur că vrei să îți ștergi contul? Această acțiune este ireversibilă.',
        cancel: 'Anulează',
      },
    },
    login: {
      tagline: 'Conectează-te la contul tău',
      emailLabel: 'Email',
      emailPlaceholder: 'tu@exemplu.ro',
      passwordLabel: 'Parolă',
      passwordPlaceholder: '••••••••',
      signIn: 'Conectare',
      signingIn: 'Se conectează…',
      errorRequired: 'Introduceți emailul și parola.',
      errorFailed: 'Autentificare eșuată. Încearcă din nou.',
    },
    footer: {
      tagline: 'Platforma ta de consultanță fiscală. Conectăm clienți cu consultanți verificați.',
      legalTitle: 'Legal',
      terms: 'Termeni și condiții',
      privacy: 'Politica de confidențialitate',
      supportTitle: 'Suport',
      contact: 'Contact',
      feedback: 'Trimite feedback',
      copyright: (year) => `© ${year} Servio. Toate drepturile rezervate.`,
    },
    profileTab: {
      avatarLabel: 'Avatar',
      bannerLabel: 'Copertă',
      clickToUpload: 'Click pentru a încărca',
      uploading: 'Se încarcă…',
      displayName: 'Nume afișat',
      bio: 'Biografie',
      hourlyRate: 'Tarif orar (€)',
      specialisation: 'Specializare',
      expertiseCategories: 'Categorii de expertiză',
      languages: 'Limbi vorbite',
      tags: 'Etichete',
      tagPlaceholder: 'Adaugă etichetă',
      addTag: 'Adaugă',
      save: 'Salvează profilul',
      saving: 'Se salvează…',
      saved: 'Salvat!',
      error: 'Nu s-a putut salva profilul.',
    },
    availabilityTab: {
      title: 'Disponibilitate',
      subtitle: 'Setează intervalele orare în care ești disponibil pentru sesiuni.',
      save: 'Salvează disponibilitatea',
      saving: 'Se salvează…',
      saved: '✓ Salvat',
      loading: 'Se încarcă…',
      days: ['Luni', 'Marți', 'Miercuri', 'Joi', 'Vineri', 'Sâmbătă', 'Duminică'],
      quickFill: 'Completare rapidă:',
      macro917: '9:00h–17:00h Zile lucrătoare',
      macroFillAll: 'Completează toate zilele',
      macroClear: 'Șterge',
      applyTo: 'Aplică pe:',
      thisWeek: 'Această săptămână',
      allWeeks: (n) => `Toate cele ${n} săpt.`,
      prev: '← Înapoi',
      next: 'Următoarea →',
      weekLabel: (n, total, range) => `Săptămâna ${n} din ${total} · ${range}`,
      today: 'Azi',
      legend: {
        available: 'Disponibil',
        blocked: 'Blocat',
        booked: 'Rezervat',
      },
      cellOpen: 'Liber',
      cellOff: 'Off',
      unsavedHint: 'Modificat — nu uita să salvezi.',
    },
  },

  en: {
    nav: {
      home: 'Home',
      myAccount: 'My Account',
      tools: 'Tools',
      signOut: 'Sign out',
      signIn: 'Sign in',
    },
    acasa: {
      slides: [
        {
          heading: 'Become a consultant',
          sub: 'Share your tax expertise and build your client base on Servio.',
          cta: 'Learn more',
        },
        {
          heading: 'Find a consultant',
          sub: 'Connect with the best tax consultants in just a few steps.',
          cta: 'Search now',
        },
      ],
    },
    catalogue: {
      stats: {
        available: 'Available consultants',
        specialisations: 'Specialisations',
        avgRate: 'Avg. hourly rate',
      },
      filters: {
        specialisation: 'Specialisation',
        maxRate: (max) => `Max rate: €${max}`,
        availableToday: 'Available today only',
        sortBy: 'Sort by',
        sortOptions: {
          relevance: 'Relevance',
          rateAsc: 'Rate (low → high)',
          rateDesc: 'Rate (high → low)',
          name: 'Name',
        },
      },
      noResults: 'No consultants found.',
    },
    consultantCard: {
      viewProfile: 'View Profile',
      perHour: '/ hr',
    },
    statusLabels: {
      pending: 'Awaiting payment',
      pending_confirmation: 'Pending confirmation',
      ping_pong: 'More info requested',
      ping_pong_final_day: 'Final day',
      auto_confirmed: 'Auto-confirmed',
      confirmed: 'Confirmed',
      in_progress: 'In progress',
      completed: 'Completed',
      cancelled: 'Cancelled',
      disputed: 'Disputed',
      closed: 'Closed',
      auto_closed: 'Auto-closed',
      retry_payment: 'Retry payment',
    },
    statusTips: {
      pending: 'Payment is in progress.',
      pending_confirmation: 'Payment received. Waiting for the consultant to confirm your session.',
      confirmed: 'The consultant has confirmed. Your session is locked in.',
      completed: 'The session has ended successfully.',
      cancelled: 'This session was cancelled.',
    },
    dashboard: {
      tabs: {
        overview: 'Overview',
        sessions: 'My Sessions',
        availability: 'Availability',
        profile: 'My Profile',
        settings: 'Account Settings',
      },
    },
    clientDashboard: {
      tabs: {
        sessions: 'My Sessions',
        settings: 'Account Settings',
      },
    },
    overview: {
      welcomeBack: (name) => `Welcome back, ${name}.`,
      activitySummary: "Here's a summary of your activity.",
      kpi: {
        upcoming: 'Upcoming sessions',
        pendingConfirmation: 'Pending confirmation',
        completedThisMonth: 'Completed this month',
        total: 'Total sessions',
      },
      upcomingTitle: 'Upcoming Sessions',
      noUpcoming: 'No upcoming sessions.',
      seeDetails: 'See Details',
    },
    sessionsTab: {
      title: 'My Sessions',
      checking: 'Checking…',
      refresh: '↻ Refresh',
      loading: 'Loading…',
      noSessions: 'No sessions.',
      filterAll: 'All',
      columns: {
        client: 'Client',
        dateTime: 'Date & Time',
        status: 'Status',
        notes: 'Notes',
        actions: 'Actions',
      },
      seeDetails: 'See Details',
      confirm: 'Confirm',
      settingUpRoom: 'Setting up room…',
      join: 'Join',
    },
    mySessionsPanel: {
      title: 'My Sessions',
      loading: 'Loading…',
      noSessions: 'No sessions yet.',
      refresh: '↻ Refresh',
      checking: 'Checking…',
      seeDetails: 'See Details',
      join: 'Join',
      cancel: 'Cancel',
      settingUpRoom: 'Setting up room…',
      confirmModal: {
        title: 'Are you sure?',
        message: 'This will cancel the session and release the time slot. This action cannot be undone.',
        goBack: 'Go back',
        confirmCancel: 'Yes, cancel session',
        cancelling: 'Cancelling…',
      },
      columns: {
        consultant: 'Consultant',
        dateTime: 'Date & Time',
        status: 'Status',
        actions: 'Actions',
      },
    },
    accountSettings: {
      financial: {
        title: 'Financial',
        loading: 'Loading…',
        active: 'Active — payments are routed automatically',
        incompleteOnboarding: 'Incomplete onboarding — complete your setup',
        stripeId: 'Stripe ID',
        completeOnboarding: 'Complete onboarding',
        checkStatus: 'Check status',
        checking: 'Checking…',
        redirecting: 'Redirecting…',
        noAccount: "You don't have a Stripe account connected. Connect one to receive payments directly in your bank account.",
        connectStripe: 'Connect Stripe account',
      },
      changeEmail: {
        title: 'Change Email Address',
        newEmail: 'New email address',
        placeholder: 'new-email@example.com',
        save: 'Update email',
        saving: 'Saving…',
        success: '✓ Email address updated.',
        error: 'An error occurred.',
      },
      changePassword: {
        title: 'Change Password',
        currentPassword: 'Current password',
        newPassword: 'New password',
        confirmPassword: 'Confirm new password',
        save: 'Update password',
        saving: 'Saving…',
        success: '✓ Password updated.',
        mismatch: 'Passwords do not match.',
        error: 'An error occurred.',
      },
      dangerZone: {
        title: 'Danger Zone',
        deleteAccount: 'Delete account',
        deleting: 'Deleting…',
        confirmMessage: 'Are you sure you want to delete your account? This action is irreversible.',
        cancel: 'Cancel',
      },
    },
    login: {
      tagline: 'Sign in to your account',
      emailLabel: 'Email',
      emailPlaceholder: 'you@example.com',
      passwordLabel: 'Password',
      passwordPlaceholder: '••••••••',
      signIn: 'Sign in',
      signingIn: 'Signing in…',
      errorRequired: 'Please enter your email and password.',
      errorFailed: 'Login failed. Please try again.',
    },
    footer: {
      tagline: 'Your tax consulting platform. We connect clients with verified consultants.',
      legalTitle: 'Legal',
      terms: 'Terms & Conditions',
      privacy: 'Privacy Policy',
      supportTitle: 'Support',
      contact: 'Contact',
      feedback: 'Send feedback',
      copyright: (year) => `© ${year} Servio. All rights reserved.`,
    },
    profileTab: {
      avatarLabel: 'Avatar',
      bannerLabel: 'Banner',
      clickToUpload: 'Click to upload',
      uploading: 'Uploading…',
      displayName: 'Display name',
      bio: 'Bio',
      hourlyRate: 'Hourly rate (€)',
      specialisation: 'Specialisation',
      expertiseCategories: 'Expertise categories',
      languages: 'Languages spoken',
      tags: 'Tags',
      tagPlaceholder: 'Add tag',
      addTag: 'Add',
      save: 'Save profile',
      saving: 'Saving…',
      saved: 'Saved!',
      error: 'Could not save profile.',
    },
    availabilityTab: {
      title: 'Availability',
      subtitle: 'Set the time slots when you are available for sessions.',
      save: 'Save Availability',
      saving: 'Saving…',
      saved: '✓ Saved',
      loading: 'Loading…',
      days: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
      quickFill: 'Quick fill:',
      macro917: '9:00h–17:00h Workdays',
      macroFillAll: 'Fill All Days',
      macroClear: 'Clear',
      applyTo: 'Apply to:',
      thisWeek: 'This week',
      allWeeks: (n) => `Full (${n} wks)`,
      prev: '← Prev',
      next: 'Next →',
      weekLabel: (n, total, range) => `Week ${n} of ${total} · ${range}`,
      today: 'Today',
      legend: {
        available: 'Available',
        blocked: 'Blocked',
        booked: 'Booked',
      },
      cellOpen: 'Open',
      cellOff: 'Off',
      unsavedHint: 'Unsaved changes — remember to save.',
    },
  },
}
